language: python
sudo: false
python:
  - "2.7"
# command to install dependencies
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
install: "pip install tox"
script: tox